version: '3.4'
services:
  minecraft:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft-server
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      VERSION: LATEST
      ALLOW_LIST: true
      LEVEL_SEED: minecraft
      LEVEL_NAME: My Minecraft
    ports:
      - 19132:19132/udp
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
  